---
apiVersion: v1
kind: Service
metadata:
  name: wp-mariadb
spec:
  selector:
    app: wp-mariadb
  ports:
    - port: 3306
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-mariadb
  labels:
    app: wp-mariadb
spec:
  template:
    metadata:
      labels:
        app: wp-mariadb
    spec:
      containers:
        - name: wp-mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: norashimi
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wp
            - name: MYSQL_PASSWORD
              value: wpadmin
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: wp-mariadb
            - name: WORDPRESS_DB_USER
              value: wp
            - name: WORDPRESS_DB_PASSWORD
              value: wpadmin
      #     volumeMounts:
      #       - name: wp-persistent-storage
      #         mountPath: /var/www/html
      # volumes:
      #   - name: wp-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: wp-pv-claim
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: wordpress-pv
#   labels:
#     type: amazonEBS
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadWriteOnce
#   awsElasticBlockStore:
#     volumeID: vol-0843fd5b02bf046cf
#     fsType: ext4
