# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: wordpress-pv
#   labels:
#     type: local
#     app: wordpress
# spec:
#   storageClassName: anything
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   awsElasticBlockStore:
#     volumeID: vol-02a14e3b500f3f18e
#     fsType: ext4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: anything
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
spec:
  storageClassName: anything
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-db-pv-claim
spec:
  storageClassName: anything
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
